#sdk: "/Users/MOHUS/rhodes"
sdkversion: 3.3.3
name: LongListTest
version: 1.0
vendor: rhomobile
build: debug
bbver: 4.6
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator5.1
  BundleIdentifier: com.rhomobile.customerapp3
  BundleURLScheme: longlisttest
  codesignidentity: iPhone Developer
  entitlements: ""
  emulatortarget: iphone
  provisionprofile: BE207A8E-BEB1-47FC-BD3B-67EE67DF4EEE

wp:
  productid: 'ede53d30-67b9-012f-fcba-3c075408aa51'
symbian:
  uid: '0xeb98fa92'
android:
  version: 2.1

extensions: ["json", "nlist"]
